### ISSUE TITLE
User can view their entries

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/code-journal#3]
## 💰 Motivation

Once a user records some journal entries, they'll want to see them.

## 📐 Plan

Display the user's journal entries in reverse chronological order so they can see the newest ones first.

## 🖼️ Wireframe

![user can view their entries](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-view-their-entries.png)

## ✅ Task List

- [x] Add a sibling `div[data-view="entries"]` to the HTML.
- [x] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [x] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [x] Check that the entries list looks good on both mobile and desktop screens.
- [x] Define a function that takes a single journal `entry` object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Remove the example HTML entries once the user's entries are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for Entries.
- [x] Add an anchor to the entries view that shows the entry form.
- [x] Ensure that submitting a new journal entry also creates a new DOM tree for it and adds it to the page.
- [x] Ensure that submitting a new journal entry automatically shows the `'entries'` view.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
