### ISSUE TITLE
User can edit an entry

### ISSUE THREAD

**Issue by angelsleung** [angelsleung/code-journal#4]
## 💰 Motivation

If a user makes a mistake when creating an entry or wants to add more notes to an entry, they should be able to edit it.

## 📐 Plan

Allow users to select an existing entry to edit and pre-populate its information into the form.

## 🖼️ Wireframe

![user can edit an entry](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/v2/user-can-edit-an-entry.png)

## ✅ Task List

- [x] Update entry rendering function to include an edit icon for each rendered entry.
- [x] Ensure that each rendered entry is given a `data-entry-id` attribute indicating which entry it is.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show the entry form if an edit icon was clicked.
- [x] Find the matching entry object in the data model and assign it to the data model's `editing` property if an edit icon was clicked.
- [x] Pre-populate the entry form with the clicked entry's values from the object found in the data model.
- [x] Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [x] Update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
